@startuml
'https://plantuml.com/sequence-diagram

title **Create a task **

skinparam roundcorner 10
skinparam ParticipantPadding 20
skinparam BoxPadding 20

boundary client

box #F5ECD5
participant CreateTaskController as controller
participant CreateTaskCommand as command
participant Task as task
participant TasksRepository as repository

client -> controller: POST /tasks
activate controller

controller -> command: execute()
activate command

command -> task: instance(title, description)
note over task: Task\n - id\n - title\n - description\n - completed\n\n + instance(title, description)\n + complete()\n + edit(title, description)\n
activate task

task --> command
deactivate task

command -> repository: save(task)
activate repository

deactivate repository
deactivate command

...some time (milliseconds) later...

controller --> client: 201 CREATED
deactivate controller

end box
@enduml